-- Supabase schema for Azura AI receptionist app

-- Demo booking requests sent from the marketing site.
create table if not exists demo_bookings (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id),
  first_name text not null,
  last_name text not null,
  email text not null,
  phone text,
  hotel_name text,
  hotel_size text,
  message text,
  preferred_date date,
  status text not null default 'pending',
  created_at timestamptz not null default now()
);

-- Contact form submissions.
create table if not exists contact_submissions (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null,
  subject text not null,
  message text not null,
  category text,
  status text not null default 'new',
  created_at timestamptz not null default now()
);

-- Newsletter subscribers.
create table if not exists newsletter_subscriptions (
  id bigint generated by default as identity primary key,
  email text not null unique,
  name text,
  is_active boolean not null default true,
  unsubscribed_at timestamptz,
  created_at timestamptz not null default now()
);

-- Pricing inquiries from prospects.
create table if not exists pricing_inquiries (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null,
  company text,
  current_plan text,
  inquiry_type text not null,
  details text,
  status text not null default 'pending',
  created_at timestamptz not null default now()
);

-- Feedback and product suggestions.
create table if not exists feedback (
  id bigint generated by default as identity primary key,
  email text not null,
  feedback_type text not null,
  title text not null,
  description text not null,
  rating int,
  status text not null default 'new',
  created_at timestamptz not null default now()
);

-- Analytics events for usage tracking.
create table if not exists analytics_events (
  id bigint generated by default as identity primary key,
  event_type text not null,
  user_email text,
  event_data jsonb,
  session_id text,
  source_url text,
  created_at timestamptz not null default now()
);

-- Receptionist configuration saved per authenticated user.
create table if not exists receptionist_settings (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id),
  property_name text,
  email text,
  phone text,
  timezone text,
  language text,
  ai_tone text,
  auto_respond boolean default true,
  escalate_to_human boolean default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table receptionist_settings enable row level security;
create policy "Users can manage their own receptionist settings"
  on receptionist_settings
  for select using (auth.uid() = user_id);
create policy "Users can insert their own receptionist settings"
  on receptionist_settings
  for insert with check (auth.uid() = user_id);
create policy "Users can update their own receptionist settings"
  on receptionist_settings
  for update using (auth.uid() = user_id) with check (auth.uid() = user_id);

-- Appointment records for the receptionist dashboard.
create table if not exists appointments (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id),
  guest_name text not null,
  guest_email text not null,
  guest_phone text,
  start_time timestamptz not null,
  end_time timestamptz not null,
  status text not null default 'pending',
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table appointments enable row level security;
create policy "Users can manage their own appointments"
  on appointments
  for select using (auth.uid() = user_id);
create policy "Users can insert appointments for themselves"
  on appointments
  for insert with check (auth.uid() = user_id);
create policy "Users can update their own appointments"
  on appointments
  for update using (auth.uid() = user_id) with check (auth.uid() = user_id);
